
# name of enviroment for this project
name: mt26
channels:
  - conda-forge

# libraries used in this project
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scipy
  - skrub
  - scikit-learn
  - prince
  - miceforest
  - hoggorm
  - matplotlib
  - seaborn
  - jupyterlab
  - ipykernel
  - catboost
  - phik
  - pyod
  - pip
  - pip:
      - scikit-na
  
  # last updated 02.02.2026
