
# name of enviroment for this project
name: mt26
channels:
  - conda-forge

# libraries used in this project
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scipy
  - skrub
  - scikit-learn        
  - hoggorm
  - matplotlib
  - seaborn
  - jupyterlab
  - ipykernel
  - catboost            
  - lightgbm
  - shap
  - phik
  - pyod
  - optuna             
  - pip
  - pip:
      - feature-engine
      - scikit-na
      - hoggormplot
      - adjustText
      - six
      - git+https://github.com/khliland/missing-methods.git
      - git+https://github.com/NMBU-Data-Science/RENT.git

  # last updated 15.04.2026
